# get the base node image
FROM node:16

# set the working dir for container
WORKDIR /frontend

# copy the json file first
COPY ./package.json /frontend

# install npm dependencies
RUN npm install
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
# copy other project files
COPY . .

# build the folder
CMD [ "npm", "run", "start" ]
