version: '3'
services: 
    backend:
        build: 
            context: .
            dockerfile: Dockerfile
        command: npm run start
        container_name: backend
        ports:
            - "3001:3000"        
        volumes: 
            - ./:/backend
            - /backend/node_modules
